# Generated by Django 3.0.3 on 2021-02-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='watch_number',
            field=models.PositiveIntegerField(default=0, verbose_name='观看数'),
        ),
    ]
